### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by tjdevries** [janestreet/vcaml#4]
Sorry, maybe I'm just doing this completely wrong, but I was trying to build this to run the examples for myself, but I wasn't able to.

When I try and run:

```
$ opam update
...
$ opam install .
vcaml on  master via 🐫 v5.0.0 (5.0.0) 
❯ opam install .               
[vcaml.v0.15.0] synchronised (no changes)
[ERROR] Package conflict!
  * Missing dependency:
    - man_in_the_middle_debugger
    unknown package

No solution found, exiting
```

Maybe there is something super obviously I need to do that I'm just not aware of because I'm relatively new at Ocaml. Would love your thoughts, thanks!

**Comment by tjdevries** [comment]
Ah, maybe I just needed to run:

```
$ opam repo add janestreet-bleeding https://ocaml.janestreet.com/opam-repository
```

That seems to have fixed it (might want to make a note somewhere in the docs. Just found it by happenstance searching the package name on sourcegraph haha)

**Comment by tjdevries** [comment]
It appears I may have spoken too soon:

```

vcaml on  master via 🐫 v4.14.1 (5.0.0) took 4s 
❯ opam install .                   
[vcaml.v0.15.0] synchronised (no changes)
The following actions will be performed:
  ∗ install jsonaf v0.15.0  [required by vcaml]
  ∗ install vcaml  v0.15.0*
===== ∗ 2 =====
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved jsonaf.v0.15.0  (cached)
⬇ retrieved vcaml.v0.15.0  (no changes)
[ERROR] The compilation of jsonaf.v0.15.0 failed at "dune build -p jsonaf -j 31".

#=== ERROR while compiling jsonaf.v0.15.0 =====================================#
# context     2.1.2 | linux/x86_64 | ocaml-base-compiler.4.14.1 | https://opam.ocaml.org#13286518
# path        ~/.opam/5.0.0/.opam-switch/build/jsonaf.v0.15.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p jsonaf -j 31
# exit-code   1
# env-file    ~/.opam/log/jsonaf-1279491-784940.env
# output-file ~/.opam/log/jsonaf-1279491-784940.out
### output ###
# (cd _build/default && /home/tjdevries/.opam/5.0.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.jsonaf.objs/byte -I /home/tjdevries/.opam/5.0.0/lib/angstrom -I /home/tjdevries/.opam/5.0.0/lib/base -I /home/tjdevries/.opam/5.0.0/lib/base/base_internalhash_types -I /home/tjdevries/.opam/5.0.0/lib/base/md5 -I /home/tjdevries/.opam/5.0.0/lib/base/shadow_stdlib -I /home/tjdevries/.opam/5.0.0/lib/bas[...]
# File "src/jsonaf.mli", line 116, characters 14-28:
# 116 |   -> ('a, 'b) Caml.Hashtbl.t
#                     ^^^^^^^^^^^^^^
# Alert deprecated: module Base.Caml
# [since 2023-01] use Stdlib instead of Caml
# File "src/jsonaf.mli", line 116, characters 14-28:
# 116 |   -> ('a, 'b) Caml.Hashtbl.t
#                     ^^^^^^^^^^^^^^
# Error: Unbound module Caml.Hashtbl



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build jsonaf v0.15.0
└─ 
╶─ No changes have been performed
```

**Comment by TyOverby** [comment]
Our libraries on github haven't been updated for OCaml 5.0 yet, it's coming soon (next few weeks?) but if you're just trying to build VCaml, I'd recommend downgrading your opam switch to OCaml 4.12

**Comment by tjdevries** [comment]
Cool, I'll give that a shot this week. I was hoping to try 5.0 to play with some of the new features and explore ocaml (I'm relatively new to the language), but it's no problem either way.

Thanks for the reply.

**Comment by tjdevries** [comment]
hmm, i wasn't able to build with 4.12 or 4.14. Sorry to be a bother

**Comment by ddickstein** [comment]
@tjdevries I will reach out to you directly and work with you on debugging your opam environment and getting it built.
